const test = require("node:test");
const assert = require("node:assert/strict");
const { buildMessages } = require("../src/prompt");
const { mergeConfig } = require("../src/config-store");
const { parseSse, requestCompletion } = require("../src/llm-client");
const { TelegramService } = require("../src/telegram-service");
test("prompt contains context and maps roles",()=>{const config=mergeConfig({business:{context:"Работаем с 9 до 18"}});const messages=buildMessages(config,[{outgoing:false,text:"Когда?"},{outgoing:true,text:"С девяти."}]);assert.match(messages[0].content,/Работаем с 9 до 18/);assert.deepEqual(messages.slice(1).map((item)=>item.role),["user","assistant"])});
test("parses OmniRoute SSE",()=>{assert.equal(parseSse('data: {"choices":[{"delta":{"content":"При"}}]}\n\ndata: {"choices":[{"delta":{"content":"вет"}}]}\n\ndata: [DONE]\n'),"Привет")});
test("requests JSON completion",async()=>{const fake=async()=>new Response(JSON.stringify({choices:[{message:{content:" OK "}}]}),{status:200,headers:{"content-type":"application/json"}});assert.equal(await requestCompletion({baseUrl:"http://local/v1",apiKey:"k",model:"m",temperature:.4,maxTokens:20},[],fake),"OK")});
test("shows a useful error when OmniRoute is unavailable",async()=>{const fake=async()=>{throw new TypeError("fetch failed")};await assert.rejects(()=>requestCompletion({baseUrl:"http://127.0.0.1:20128/v1",model:"m"},[],fake),/Нет соединения с OmniRoute/)});
test("chat allow and deny modes are applied",()=>{const service=new TelegramService({getConfig:()=>({}),saveConfig:()=>{},emit:()=>{}});assert.equal(service.isChatAllowed("1",{chats:{mode:"allow",selectedIds:["1"],knownIds:["1"],allowNewChats:false}}),true);assert.equal(service.isChatAllowed("2",{chats:{mode:"allow",selectedIds:["1"],knownIds:["1","2"],allowNewChats:false}}),false);assert.equal(service.isChatAllowed("1",{chats:{mode:"deny",selectedIds:["1"],knownIds:["1"],allowNewChats:true}}),false);assert.equal(service.isChatAllowed("new",{chats:{mode:"deny",selectedIds:[],knownIds:[],allowNewChats:true}}),true)});
