let state;
let loadedChats=[];
const $ = (id) => document.getElementById(id);
function toast(message){const element=$("toast");element.textContent=message;element.classList.add("show");setTimeout(()=>element.classList.remove("show"),2500)}
function appendLog(entry){const line=document.createElement("div");line.className=`log-entry ${entry.level||"info"}`;line.textContent=`${new Date().toLocaleTimeString()} — ${entry.message}`;$("log").prepend(line);while($("log").children.length>50)$("log").lastChild.remove()}
function updateStatus(status){const element=$("status");element.classList.toggle("online",Boolean(status.connected));element.querySelector("strong").textContent=status.connected?`Подключён${status.displayName?` · ${status.displayName}`:""}`:"Отключён"}
function readForm(){const checks=[...document.querySelectorAll('.chat-check')];return{telegram:{apiId:$("apiId").value.trim(),apiHash:$("apiHash").value.trim(),phone:$("phone").value.trim()},llm:{baseUrl:$("baseUrl").value.trim(),apiKey:$("apiKey").value.trim(),model:$("model").value.trim(),temperature:Number($("temperature").value),maxTokens:Number($("maxTokens").value)},business:{context:$("businessContext").value,instructions:$("instructions").value},automation:{enabled:$("enabled").checked,replyDelaySeconds:Number($("replyDelaySeconds").value),historyLimit:state.config.automation.historyLimit,manualPauseEnabled:$("manualPauseEnabled").checked,manualPauseMinutes:Number($("manualPauseMinutes").value)},chats:{mode:$("chatMode").value,selectedIds:checks.length?checks.filter((item)=>item.checked).map((item)=>item.value):(state.config.chats.selectedIds||[]),knownIds:state.config.chats.knownIds||[],allowNewChats:$("allowNewChats").checked,historyAll:$("historyAll").checked,historyLimit:Number($("chatHistoryLimit").value),maxContextChars:state.config.chats.maxContextChars||60000}}}
function fillForm(c){$("apiId").value=c.telegram.apiId;$("apiHash").value=c.telegram.apiHash;$("phone").value=c.telegram.phone;$("baseUrl").value=c.llm.baseUrl;$("apiKey").value=c.llm.apiKey;$("model").value=c.llm.model;$("temperature").value=c.llm.temperature;$("maxTokens").value=c.llm.maxTokens;$("businessContext").value=c.business.context;$("instructions").value=c.business.instructions;$("enabled").checked=c.automation.enabled;$("replyDelaySeconds").value=c.automation.replyDelaySeconds;$("manualPauseEnabled").checked=c.automation.manualPauseEnabled;$("manualPauseMinutes").value=c.automation.manualPauseMinutes;$("manualPauseMinutes").disabled=!c.automation.manualPauseEnabled;$("chatMode").value=c.chats.mode;$("allowNewChats").checked=c.chats.allowNewChats;$("historyAll").checked=c.chats.historyAll;$("chatHistoryLimit").value=c.chats.historyLimit;$("chatHistoryLimit").disabled=c.chats.historyAll}
function renderChats(){const selected=new Set((state.config.chats.selectedIds||[]).map(String));const mode=$("chatMode").value;$("chatList").replaceChildren(...loadedChats.map((chat)=>{const label=document.createElement("label");label.className="chat-item";const input=document.createElement("input");input.type="checkbox";input.className="chat-check";input.value=chat.id;input.checked=selected.has(chat.id);const box=document.createElement("div");const name=document.createElement("strong");name.textContent=chat.title;const detail=document.createElement("small");detail.textContent=`${chat.username?`@${chat.username} · `:""}${chat.id} · ${mode==="allow"?"галочка разрешает ответы":"галочка запрещает ответы"}`;box.append(name,detail);label.append(input,box);return label}))}
async function save(){state.config=await window.aiUserBot.saveConfig(readForm());toast("Сохранено")}
async function run(action){try{await action()}catch(error){appendLog({level:"error",message:error.message});toast(error.message)}}
document.querySelectorAll(".tab").forEach((button)=>button.addEventListener("click",()=>{document.querySelectorAll(".tab,.panel").forEach((element)=>element.classList.remove("active"));button.classList.add("active");$(button.dataset.tab).classList.add("active")}));
$("saveControl").onclick=()=>run(save);$("saveContext").onclick=()=>run(save);$("saveLlm").onclick=()=>run(save);
$("saveTelegram").onclick=()=>run(async()=>{await save();appendLog({message:"Подключение к Telegram…"});await window.aiUserBot.connect()});
$("connect").onclick=()=>run(()=>window.aiUserBot.connect());$("disconnect").onclick=()=>run(()=>window.aiUserBot.disconnect());
$("logout").onclick=()=>run(async()=>{await window.aiUserBot.logout();toast("Сессия Telegram удалена")});
$("testLlm").onclick=()=>run(async()=>{await save();$("testResult").textContent="Запрос…";$("testResult").textContent=await window.aiUserBot.testLlm()});
$("historyAll").onchange=()=>{$("chatHistoryLimit").disabled=$("historyAll").checked};
$("chatMode").onchange=renderChats;
$("manualPauseEnabled").onchange=()=>{$("manualPauseMinutes").disabled=!$("manualPauseEnabled").checked};
$("loadChats").onclick=()=>run(async()=>{loadedChats=await window.aiUserBot.loadChats();const fresh=await window.aiUserBot.getState();state.config.chats=fresh.config.chats;renderChats();toast(`Загружено чатов: ${loadedChats.length}`)});
$("selectAllChats").onclick=()=>document.querySelectorAll(".chat-check").forEach((item)=>{item.checked=true});
$("clearAllChats").onclick=()=>document.querySelectorAll(".chat-check").forEach((item)=>{item.checked=false});
$("saveChats").onclick=()=>run(save);
$("openDashboard").onclick=()=>run(()=>window.aiUserBot.openDashboard());
$("restartOmniRoute").onclick=()=>run(async()=>{updateOmniRoute({running:false,dashboardUrl:"Запуск…"});updateOmniRoute(await window.aiUserBot.startOmniRoute())});
$("authSubmit").onclick=(event)=>{event.preventDefault();run(async()=>{await window.aiUserBot.submitAuth($("authValue").value);$("authDialog").close()})};
function updateOmniRoute(value){$("omniDot").classList.toggle("online",Boolean(value.running));$("omniStatusText").textContent=value.running?"OmniRoute работает":"OmniRoute не запущен";$("omniStatusUrl").textContent=value.dashboardUrl||"http://127.0.0.1:20128";if(value.apiUrl&&state){state.config.llm.baseUrl=value.apiUrl;$("baseUrl").value=value.apiUrl}}
window.aiUserBot.onEvent(({type,data})=>{if(type==="log")appendLog(data);if(type==="status")updateStatus(data);if(type==="omniroute-status")updateOmniRoute(data);if(type==="chats-updated"){loadedChats=data;window.aiUserBot.getState().then((fresh)=>{state.config.chats=fresh.config.chats;renderChats()})}if(type==="auth-request"){$("authTitle").textContent=data.type==="password"?"Пароль 2FA":"Код Telegram";$("authMessage").textContent=data.message;$("authValue").value="";$("authValue").type=data.type==="password"?"password":"text";$("authDialog").showModal();$("authValue").focus()}});
window.aiUserBot.getState().then(async(initial)=>{state=initial;fillForm(state.config);updateStatus(state.status);appendLog({message:"Приложение запущено"});updateOmniRoute(await window.aiUserBot.getOmniRouteStatus())});
